[
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "C[SH+]C=Cc1ccccc1.F[B-](F)(F)F",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 704, in optimizeGeometry\n    raise GeomOptNotConvergedError(\"Optimizer.optimizeGeometry() failed to converge.\")\ngeometric.errors.GeomOptNotConvergedError: Optimizer.optimizeGeometry() failed to converge.\n"
    },
    {
        "smiles": "CCCC[Sn](C=CCOC(=O)/C=C\\C(=O)[O-])(CCCC)CCCC",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "C[SH+]C=Cc1ccccc1.F[B-](F)(F)F",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "CCCC[Sn](C=CCOC(=O)/C=C\\C(=O)[O-])(CCCC)CCCC",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "C=Cc1cc(O)ccc1O.O=C(O)c1ccccc1.O=C(O)c1ccccc1",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "C=C(C)C(=O)[O-].[K+]",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "C=C(CC(=O)[O-])C(=O)[O-].CCCC[Sn+](CCCC)CCCC.CCCC[Sn+](CCCC)CCCC",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "C=CC(=O)NC(C)(C)CC(=O)[O-].[Na+]",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 694, in optimizeGeometry\n    self.step()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 451, in step\n    iopt = brent_wiki(froot.evaluate, 0.0, iopt, froot.target, cvg=0.1, verbose=params.verbose)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/step.py\", line 80, in brent_wiki\n    raise RuntimeError('Not bracketed')\nRuntimeError: Not bracketed\n"
    },
    {
        "smiles": "C=CC(=O)OC[c-]1cccc1.[Fe+2].c1cc[cH-]c1",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 704, in optimizeGeometry\n    raise GeomOptNotConvergedError(\"Optimizer.optimizeGeometry() failed to converge.\")\ngeometric.errors.GeomOptNotConvergedError: Optimizer.optimizeGeometry() failed to converge.\n"
    },
    {
        "smiles": "C=CC(=O)[O-].C=CC(=O)[O-].[Zn+2]",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 691, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "C=CC[N+](C)(C)CC=C.[Cl-]",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "C=C[n+]1ccn(CC)c1.[I-]",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 691, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "C[SH+]C=Cc1ccccc1.F[B-](F)(F)F",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "CCCC[Sn](C=CCOC(=O)/C=C\\C(=O)[O-])(CCCC)CCCC",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "C[SH+]C=Cc1ccccc1.F[B-](F)(F)F",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "CCCC[Sn](C=CCOC(=O)/C=C\\C(=O)[O-])(CCCC)CCCC",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 691, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "C=Cc1cc(O)ccc1O.O=C(O)c1ccccc1.O=C(O)c1ccccc1",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "C[SH+]C=Cc1ccccc1.F[B-](F)(F)F",
        "error": "geomeTRIC run_json error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/run_json.py\", line 258, in geometric_run_json\n    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 778, in Optimize\n    return optimizer.optimizeGeometry()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 696, in optimizeGeometry\n    self.calcEnergyForce()\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/optimize.py\", line 282, in calcEnergyForce\n    spcalc = self.engine.calc(self.X, self.dirname, read_data=(self.Iteration==0))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1473, in calc\n    return self.calc_new(coords, dirname)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/geometric/engine.py\", line 1464, in calc_new\n    raise QCEngineAPIEngineError(\"QCEngineAPI computation did not execute correctly. Message: \" + ret[\"error\"][\"error_message\"])\ngeometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/util.py\", line 117, in compute_wrapper\n    yield metadata\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/compute.py\", line 108, in compute\n    output_data = executor.compute(input_data, config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/qcengine/programs/xtb.py\", line 72, in compute\n    output = run_qcschema(input_data)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/xtb/qcschema/harness.py\", line 214, in run_qcschema\n    return qcel.models.AtomicResult(**ret_data, stdout=output)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maraw/anaconda3/envs/morfeus2/lib/python3.11/site-packages/pydantic/v1/main.py\", line 341, in __init__\n    raise validation_error\npydantic.v1.error_wrappers.ValidationError: 1 validation error for AtomicResult\nreturn_result\n  cannot reshape array of size 1 into shape (3) (type=value_error)\n\n"
    },
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "CCCC[Sn](C=CCOC(=O)/C=C\\C(=O)[O-])(CCCC)CCCC",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpdsr_s0st': Too many open files"
    },
    {
        "smiles": "C=Cc1cc(O)ccc1O.O=C(O)c1ccccc1.O=C(O)c1ccccc1",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmppzsfsd26': Too many open files"
    },
    {
        "smiles": "C=C(CC(=O)[O-])C(=O)[O-].CCCC[Sn+](CCCC)CCCC.CCCC[Sn+](CCCC)CCCC",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    },
    {
        "smiles": "C=CC(=O)[O-].C=CC(=O)[O-].[Zn+2]",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    },
    {
        "smiles": "C=CC[N+](C)(C)CC=C.[Cl-]",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    },
    {
        "smiles": "C=Cc1cc(O)ccc1O.O=C(O)c1ccccc1.O=C(O)c1ccccc1",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    },
    {
        "smiles": "CCCC[Sn](C=CCOC(=O)/C=C\\C(=O)[O-])(CCCC)CCCC",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmp95taispd': Too many open files"
    },
    {
        "smiles": "O=C(O)c1cccc(C(=O)O)c1.[Cl-].[Cl-]",
        "error": "Following atoms are too close: [(12, 13, 0.0)]"
    },
    {
        "smiles": "C=C(C)C(=O)OCC[N+](C)(C)C.[Cl-]",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpw9c5kt_6': Too many open files"
    },
    {
        "smiles": "CCCC[Sn+2]CCCC.O=C([O-])/C=C\\C(=O)[O-]",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmp48vz7ixk': Too many open files"
    },
    {
        "smiles": "C=C(C)C(=O)NCCC[N+](C)(C)C.[Cl-]",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    },
    {
        "smiles": "C=C(C)C(=O)O.C=C(C)C(=O)O.OCCO",
        "error": "Following atoms are too close: [(1, 7, 0.06201144565622211)]"
    },
    {
        "smiles": "C=C(C)C(=O)O.C=C(C)C(=O)O.OCCOCCO",
        "error": "Following atoms are too close: [(1, 7, 0.06035768409354296), (3, 9, 0.07315241209370413)]"
    },
    {
        "smiles": "C=C(C)C(=O)O.C=C(C)C(=O)O.OCCOCCOCCO",
        "error": "Following atoms are too close: [(25, 32, 0.040755662507700935)]"
    },
    {
        "smiles": "C=C(C)C(=O)O.C=C(C)C(=O)O.OCCOCCOCCOCCO",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    },
    {
        "smiles": "C=C(C)C(=O)OCC.C=C(CCC)COCCP(=O)(OC)OC",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpkbrjeg65': Too many open files"
    },
    {
        "smiles": "C=C(C)C(=O)OCC[N+](C)(C)CCCCCCCCCCC.[Br-]",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpz52c1nsr': Too many open files"
    },
    {
        "smiles": "C=C(C)C.C=CC(=O)OC(CC)CCCCC",
        "error": "Following atoms are too close: [(18, 30, 0.0719040237804365)]"
    },
    {
        "smiles": "C=CC(=O)[O-].C=CC(=O)[O-].[Co+2]",
        "error": "Following atoms are too close: [(0, 5, 0.07634959023725185)]"
    },
    {
        "smiles": "C=CC(=O)[O-].C=CC(=O)[O-].[Cu+2]",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmph_tpdviy': Too many open files"
    },
    {
        "smiles": "C=CC(=O)[O-].C=CC(=O)[O-].[Ni+2]",
        "error": "Following atoms are too close: [(11, 14, 0.08524655604108786)]"
    },
    {
        "smiles": "C=COCC1CO1.OCCO",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmp168ifkvv': Too many open files"
    },
    {
        "smiles": "CC(C)=CC[NH3+].[Cl-]",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpgrq71ukg': Too many open files"
    },
    {
        "smiles": "C=Cc1cc[cH-]c1.[Fe].[cH-]1[cH-][cH-][cH-][cH-]1",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpwdq3ttyn': Too many open files"
    },
    {
        "smiles": "S1(=O)(=O)C(CCC1)C(=O)O.C(C(=C)C)(=O)O",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmp6ggr9gfq': Too many open files"
    },
    {
        "smiles": "C(=C)[C-]1C=CC=C1.[CH-]1C=CC=C1.[Fe+2]",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmp2san88rz': Too many open files"
    },
    {
        "smiles": "C(C(=C)CC(=O)[O-])(=O)[O-].C(CCC)[Sn+](CCCC)CCCC.C(CCC)[Sn+](CCCC)CCCC",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpx7gkldp4': Too many open files"
    },
    {
        "smiles": "C(C1=CC=CC=C1)(=O)O.C(C1=CC=CC=C1)(=O)O.C(=C)C1=C(O)C=CC(=C1)O",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmp677tvzvq': Too many open files"
    },
    {
        "smiles": "C(C=C)(=O)OC[C-]1C=CC=C1.[CH-]1C=CC=C1.[Fe+2]",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmphq2j6sr3': Too many open files"
    },
    {
        "smiles": "[Cl-].C[N+](CC=C)(CC=C)C",
        "error": "Single point calculation failed:\n-4- xtb_calculator_singlepoint: Electronic structure method terminated\n-3- scf: Self consistent charge iterator did not converge\n-2- xtb_calculator_newWavefunction: EEQ guess failed, falling back to SAD guess\n-1- xtb_api_setOutput: Cannot open file '/var/folders/tv/b0y73fwd4zn44s4jmxl5169w0000gn/T/tmpz3te0i57': Too many open files"
    },
    {
        "smiles": "C=C(C)C(=O)[O-].CCCC[Sn+](CCCC)CCCC",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    },
    {
        "smiles": "C=C(CC(=O)O[Sn](CCCC)(CCCC)CCCC)C(=O)O[Sn](CCCC)(CCCC)CCCC",
        "error": "Single point calculation failed:\n-2- xtb_calculator_singlepoint: Electronic structure method terminated\n-1- scf: Self consistent charge iterator did not converge"
    }
]